const mongoose = require('mongoose');

const ArticleSchema = new mongoose.Schema({
    title: String,
    content: String, // Replace with actual content from the article
    summary: String, // This will be generated by the LLM
    credibilityScore: Number // The credibility score
});

const Article = mongoose.model('Article', ArticleSchema);

module.exports = { Article };
